### ISSUE TITLE
HDAvatars - Only loads up higher res avatars when plugin is first loaded, and not all the time.

### ISSUE THREAD

**Issue by Otaku-2** [noodlebox/betterdiscord-plugins#12]
Can be seen more clearly with the Avatar Hover plugin, which works well with this plugin.

**Comment by noodlebox** [comment]
It looks like Discord made a change which improves the default avatar quality, while causing it to be worse for users of this plugin.

So, for now, this plugin is made obsolete by improvements from Discord (a good thing), and you should disable it, unless I make any further improvements in the future.

**Comment by noodlebox** [comment]
Made a small change that should avoid the quality reduction when using this plugin.

Still, this plugin should no longer be necessary unless you're using a theme that displays avatars at a larger than normal size (>256px).
