### ISSUE TITLE
Owner Tags

### ISSUE THREAD

**Issue by Zekken01** [noodlebox/betterdiscord-plugins#2]
Owner tags seem to not work anymore.

**Comment by noodlebox** [comment]
Try updating it to the latest version (1.2.3). It fixes some issues introduced by the last Discord update.

**Comment by Zekken01** [comment]
ok, it works. btw I like what you did for if you accidentally run it. I accidentally opened thinking it would open with a text editor. XD

**Comment by noodlebox** [comment]
Yup, thought that might come in handy. :P
