### ISSUE TITLE
StaticAvatars: Stopped stopping gif avatars

### ISSUE THREAD

**Issue by Otaku-2** [noodlebox/betterdiscord-plugins#26]
Dunno why, maybe there was a sneak-update that broke it (as usual)

**Comment by noodlebox** [comment]
Discord is updating to a new version of ReactJS, it breaks some of the uglier things a few of my plugins do. StaticAvatars should still work though if you have the latest version of the plugin (2.0.0). These Discord updates will break the older ones. (#27)

**Comment by Midoko** [comment]
@Otaku-2 random but could you please tell the origins of your avatar? would appreciate it.
