### ISSUE TITLE
ReactJS update breaks plugins that depend on getOwnerInstance

### ISSUE THREAD

**Issue by noodlebox** [noodlebox/betterdiscord-plugins#27]
Discord is now using a newer version of ReactJS, which rearranges some internals slightly. This breaks OwnerTag and AutoPlayGifs (animated avatars only). This also breaks the pre-2.0 version of StaticAvatars, but the latest version is unaffected.

**Comment by vperpl** [comment]
plz fix owner tags ty.

**Comment by yorik100** [comment]
please fix owner tags

**Comment by nihaals** [comment]
OwnerTag: Doesn't have tag in mutual servers list and next to name in member list

**Comment by noodlebox** [comment]
This issue is fixed for OwnerTag in 1.3.4 (thanks, @Inve1951)
