### ISSUE TITLE
Autoplay Gifs broke because of React 16

### ISSUE THREAD

**Issue by Abyss1992** [noodlebox/betterdiscord-plugins#28]

**Comment by noodlebox** [comment]
Thanks for reporting, but I already have an issue open for this. (duplicate of #27)

**Comment by Abyss1992** [comment]
Cool any ETA or is it just when ever you get to it?

**Comment by noodlebox** [comment]
I'll probably get to this later today, it just depends on how much digging around I have to do in the new code.
