### ISSUE TITLE
FIX OWNER TAGS

### ISSUE THREAD

**Issue by 011011000111010101111000** [noodlebox/betterdiscord-plugins#31]
Fix owner tags or i'll do it myself

i'm kidding I don't know shit about coding or anything but plleaaasseee fix it ;-;

*flips table and walks away*

**Comment by noodlebox** [comment]
I know you're kidding, but it is an open source project. You or anyone else capable that *can* fix it can make a pull request that I'll happily merge. Short of that, it looks like upcoming Discord changes are going to break a few other things again, so I'll be looking at this stuff again soon™. (Duplicate of #27.)
