### ISSUE TITLE
AutoPlayGifs: Mixing up replace & combine modes

### ISSUE THREAD

**Issue by GenesisAria** [noodlebox/betterdiscord-plugins#34]
. . . even when the gif itself is a set to one or t'other. Result is a sea of dead pixels, or all previous frames showing through transparency. I added a couple examples of images with reversed roles, Chief is a spam of black pixels, and Cirno all frames combine.  They work fine outside of discord, or with plugin disabled.

![halo](https://user-images.githubusercontent.com/25147974/32419077-34fed752-c229-11e7-8741-5a2562dc198b.gif)
![chiruno](https://user-images.githubusercontent.com/25147974/32419078-3f0c5594-c229-11e7-9c50-9eb0353ff61f.gif)

**Comment by noodlebox** [comment]
None of this should have anything to do with the AutoPlayGifs plugin.

**Comment by noodlebox** [comment]
I also can't replicate that here. The plugin has nothing to do with interpreting the GIF format. If you're seeing anything like this, it most likely has to do with Discord's proxy servers which resize images for displaying in the client.
