### ISSUE TITLE
AutoPlay Gif not working

### ISSUE THREAD

**Issue by egorbunovs** [noodlebox/betterdiscord-plugins#35]
With the latest Discord app - AutoPlay Gif plugin is not working.

**Comment by diydavindra** [comment]
Same issue here.

**Comment by SoggieWafflz** [comment]
it's working for posted gifs, but my avatar still animates on hover, and looking at the closed issues it seems to have been added as a feature

**Comment by noodlebox** [comment]
This plugin is mostly obsolete now so I haven't been supporting it, but if you still want avatars to always animate, try the rewrite by Zerebos.

https://github.com/rauenzi/BetterDiscordAddons/tree/master/Plugins/AutoPlayGifs

**Comment by Firefox289** [comment]
still doesnt work

**Comment by noodlebox** [comment]
@Firefox289 If you want GIFs to animate all the time, check your Discord settings. This has been a vanilla feature for years. if you want avatars to animate all the time, you'll probably want to check out the other plugin linked above.

**Comment by xosageox** [comment]
its not working. is there a way it can be fixed or i can get a different one that works?

**Comment by 3laak** [comment]
> 

I have the same problem it works only if I put the cursor on it... can someone help us :'(
