### ISSUE TITLE
Silent Typing: Apply only to specific channels

### ISSUE THREAD

**Issue by kmddd59** [noodlebox/betterdiscord-plugins#36]
sorry I made a new issue I don't know how to contact you personally but I was looking to make a option to keep silent typing off for whitelisted users so that only some people will know that I am typing
same for servers? maybe just a thought I had because one person I know really hates when it is off and I always want my typing off

**Comment by noodlebox** [comment]
If you mean changing the behavior for certain DMs or servers/channels, that should be doable, though I don't have any plans to add something like that myself.

**Comment by kmddd59** [comment]
Ok thanks

**Comment by Vastrix** [comment]
I too would very much love to see this feature! :)  
Maybe in the form of a button?  

Great plugin tho!

**Comment by Nomkid** [comment]
Please add this!

**Comment by fghsgh** [comment]
^ my friend there is getting panic attacks from not knowing when I'm typing
