### ISSUE TITLE
Silent Typing Error 

### ISSUE THREAD

**Issue by anh9000** [noodlebox/betterdiscord-plugins#44]
It was working fine last night and then when I launched Discord i had gotten this ? This is after replacing the .js with the new one posted here a few hours ago.

![image](https://user-images.githubusercontent.com/8799430/41047079-c3bed080-6979-11e8-8e95-747759765eef.png)

**Comment by noodlebox** [comment]
That means you downloaded it incorrectly. Make sure to save the "Raw" file:
<https://raw.githubusercontent.com/noodlebox/betterdiscord-plugins/master/SilentTyping.plugin.js>
