### ISSUE TITLE
KawaiiEmotes: Broken emotes / no preview list

### ISSUE THREAD

**Issue by Yentis** [noodlebox/betterdiscord-plugins#45]
The latest discord update seems to have broken the emotes displaying (only emotes not contained within stock betterdiscord), rauenzi's betterdiscord fork also had broken emotes but seems to have fixed it now (https://github.com/rauenzi/BetterDiscordApp).

The list that shows when you start typing in emote names was also broken a few months back.

I'm using the latest 0.4.7 version.

**Comment by noodlebox** [comment]
A few more class names changed, so those need to be updated.
