### ISSUE TITLE
LineNumbers - Doesn't copy blank lines properly

### ISSUE THREAD

**Issue by nirewen** [noodlebox/betterdiscord-plugins#48]
**Issue**:
[Line Numbers plugin](/noodlebox/betterdiscord-plugins/blob/master/LineNumbers.plugin.js) is not copying blank lines correctly

**Expected result**:
When copied a code, blank lines should stay

**Actual result**:
Blank lines are not copied

**Steps to reproduce**:
1. Paste a code with plugin enabled.
2. The code must have a blank line
3. Copy the code to the clipboard
4. Notice the blank lines were not copied, but instead were removed completely

**Screenshots**:
With the plugin enabled: 
![imagem](https://user-images.githubusercontent.com/8761479/45392276-fe70ee00-b5fc-11e8-8d9e-93bc158fa12a.png)
*Blank lines were not copied*

Without the plugin enabled:
![imagem](https://user-images.githubusercontent.com/8761479/45392316-2d875f80-b5fd-11e8-9117-2932234c7a80.png)
*Blank lines were copied*

**Comment by shinji257** [comment]
I got a fix for this issue.  Going to submit a PR for this in a moment.
