### ISSUE TITLE
silent typing: add button to title bar

### ISSUE THREAD

**Issue by bobthehuman** [noodlebox/betterdiscord-plugins#57]
it would be cool if there was a button on the title bar you could click to toggle silent typing

**Comment by catvskid** [comment]
uh, i bet the creator of the plugins is almost dead. Because, it's almost months he's not answering people sooo no hope i guess sorry. I could recommend yourself do it, isn't hard at all

**Comment by noodlebox** [comment]
I merged a pull request a few days ago. My focus has been on other projects lately, so my main goal here is maintaining existing functionality for those plugins that haven't been made obsolete yet by features in vanilla Discord. Implementing new features is a far lower priority. If you have something to contribute though, I'll happily take a look.
