### ISSUE TITLE
SilentTyping.plugin is not working on latest Better Discord

### ISSUE THREAD

**Issue by aabd2** [noodlebox/betterdiscord-plugins#60]
SilentTyping.plugin is not working on latest Better Discord.

Metadata was not found is the error when adding it to plugins folder.

**Comment by noodlebox** [comment]
Was this working for you on an older version and stopped working when you updated BetterDiscord?

**Comment by aabd2** [comment]
I haven't tried it on older version. I just took the latest BetterDiscord from Github that there was released on March 3. Now there seems to be even newer release from 19th of April.
