### ISSUE TITLE
SilentTyping.plugin.js for the other Users

### ISSUE THREAD

**Issue by seppl-de** [noodlebox/betterdiscord-plugins#61]
Hello and thank u for the nice plugin,

for me its a stress factor when I see that several people are writing. I would appreciate it if you develop a plugin or expand this plugin and introduce the function that I no longer have to see it. That will be very nice

Thank u!

**Comment by noodlebox** [comment]
Glad you like the plugin!

If you don't want to see notifications that *others* are typing, this can be accomplished very easily without a plugin. You just need to add a small snippet of CSS to your Custom CSS or theme. This should do it:

```css
.typing-2GQL18 {
  display: none;
}
```

If you have any trouble integrating it into your existing CSS, someone in the BD support server should be able to help!

**Comment by seppl-de** [comment]
Thank u that works perfectly but i miss one. I still can see the animation of the "3 Points" on the avatar.

**Comment by noodlebox** [comment]
It might be possible to solve that with pure CSS as well, but I'm not sure without looking more closely at it. Either way, it is outside the scope of what I want to do with this plugin. I hope you do find something that works!

**Comment by seppl-de** [comment]
Thats okay. Thx for ur help!
